export interface StockInfo {
  symbol: string;
  name: string;
  description: string;
  assetType: "stock" | "crypto";
  // Crypto only: the two data providers use different symbol conventions for
  // the same asset (Finnhub wants "BINANCE:BTCUSDT", Twelve Data wants
  // "BTC/USD"). Stocks use the same ticker on both, so these stay undefined.
  quoteSymbol?: string;
  candleSymbol?: string;
}

export const ALL_STOCKS: StockInfo[] = [
  // Technology
  { symbol: "AAPL", name: "Apple Inc.", description: "Designs iPhones, Macs, and other consumer electronics, alongside services like the App Store and Apple Music.", assetType: "stock" },
  { symbol: "MSFT", name: "Microsoft Corp.", description: "Makes Windows, Office, and Azure cloud services, with a growing focus on AI products.", assetType: "stock" },
  { symbol: "GOOGL", name: "Alphabet Inc.", description: "Parent company of Google Search, YouTube, and Android, with major investments in AI and cloud computing.", assetType: "stock" },
  { symbol: "AMZN", name: "Amazon.com Inc.", description: "E-commerce and cloud computing giant, also known for AWS, Prime, and Alexa.", assetType: "stock" },
  { symbol: "NVDA", name: "NVIDIA Corp.", description: "Designs GPUs widely used in gaming, data centers, and AI model training.", assetType: "stock" },
  { symbol: "META", name: "Meta Platforms Inc.", description: "Owns Facebook, Instagram, and WhatsApp, and is investing heavily in AI and virtual/augmented reality.", assetType: "stock" },
  { symbol: "TSLA", name: "Tesla Inc.", description: "Electric vehicle manufacturer that also develops energy storage and autonomous driving technology.", assetType: "stock" },
  { symbol: "ADBE", name: "Adobe Inc.", description: "Software company known for Photoshop, Acrobat, and its Creative Cloud subscription suite.", assetType: "stock" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", description: "Networking hardware and software company that builds much of the internet's core infrastructure.", assetType: "stock" },
  { symbol: "INTC", name: "Intel Corp.", description: "Semiconductor company that designs and manufactures computer processors and chips.", assetType: "stock" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", description: "Designs CPUs and GPUs, competing directly with Intel and NVIDIA in computing hardware.", assetType: "stock" },
  { symbol: "CRM", name: "Salesforce Inc.", description: "Cloud-based customer relationship management (CRM) software provider for businesses.", assetType: "stock" },
  { symbol: "ORCL", name: "Oracle Corp.", description: "Enterprise software and cloud infrastructure company, known for its database products.", assetType: "stock" },
  { symbol: "IBM", name: "IBM Corp.", description: "Enterprise technology company offering cloud computing, AI, and consulting services.", assetType: "stock" },
  { symbol: "NOW", name: "ServiceNow Inc.", description: "Cloud software platform that automates enterprise IT, HR, and customer service workflows.", assetType: "stock" },
  { symbol: "INTU", name: "Intuit Inc.", description: "Makes TurboTax, QuickBooks, and Credit Karma for consumer and small business finance.", assetType: "stock" },
  { symbol: "SNOW", name: "Snowflake Inc.", description: "Cloud-based data warehousing and analytics platform.", assetType: "stock" },
  { symbol: "PLTR", name: "Palantir Technologies Inc.", description: "Builds data analytics and AI software for government and enterprise clients.", assetType: "stock" },
  { symbol: "SHOP", name: "Shopify Inc.", description: "E-commerce platform that lets businesses build and run online stores.", assetType: "stock" },
  { symbol: "TXN", name: "Texas Instruments Inc.", description: "Designs and manufactures analog and embedded processing semiconductors.", assetType: "stock" },
  { symbol: "QCOM", name: "Qualcomm Inc.", description: "Designs mobile chipsets and wireless technology used in smartphones worldwide.", assetType: "stock" },
  { symbol: "AVGO", name: "Broadcom Inc.", description: "Semiconductor and infrastructure software company serving networking, wireless, and data center markets.", assetType: "stock" },
  { symbol: "MU", name: "Micron Technology Inc.", description: "Manufactures memory and storage chips, including DRAM and NAND flash.", assetType: "stock" },
  { symbol: "AMAT", name: "Applied Materials Inc.", description: "Supplies equipment and services used to manufacture semiconductor chips.", assetType: "stock" },
  { symbol: "ADI", name: "Analog Devices Inc.", description: "Designs analog, mixed-signal, and digital signal processing chips.", assetType: "stock" },
  { symbol: "PANW", name: "Palo Alto Networks Inc.", description: "Cybersecurity company providing network security and cloud protection.", assetType: "stock" },
  { symbol: "CRWD", name: "CrowdStrike Holdings Inc.", description: "Cloud-based endpoint security and threat detection platform.", assetType: "stock" },
  { symbol: "FTNT", name: "Fortinet Inc.", description: "Develops cybersecurity hardware and software, including firewalls.", assetType: "stock" },
  { symbol: "WDAY", name: "Workday Inc.", description: "Cloud software for human resources and financial management.", assetType: "stock" },
  { symbol: "TEAM", name: "Atlassian Corp.", description: "Makes Jira, Confluence, and Trello for software and project team collaboration.", assetType: "stock" },
  { symbol: "ZM", name: "Zoom Communications Inc.", description: "Video conferencing and online meeting platform.", assetType: "stock" },
  { symbol: "DOCU", name: "DocuSign Inc.", description: "Provides electronic signature and digital agreement software.", assetType: "stock" },
  { symbol: "NET", name: "Cloudflare Inc.", description: "Provides content delivery, DDoS protection, and internet security services.", assetType: "stock" },
  { symbol: "DDOG", name: "Datadog Inc.", description: "Cloud monitoring and analytics platform for developers and IT teams.", assetType: "stock" },
  { symbol: "SPOT", name: "Spotify Technology S.A.", description: "Audio streaming service offering music and podcasts.", assetType: "stock" },
  { symbol: "ABNB", name: "Airbnb Inc.", description: "Online marketplace for short-term lodging and travel experiences.", assetType: "stock" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", description: "Parent of Booking.com, Priceline, and Kayak travel booking sites.", assetType: "stock" },
  { symbol: "EA", name: "Electronic Arts Inc.", description: "Video game publisher known for FIFA/EA Sports FC, Madden, and The Sims.", assetType: "stock" },
  { symbol: "TTWO", name: "Take-Two Interactive Software Inc.", description: "Video game publisher behind Grand Theft Auto and NBA 2K.", assetType: "stock" },
  { symbol: "ROKU", name: "Roku Inc.", description: "Makes streaming devices and operates an ad-supported streaming platform.", assetType: "stock" },
  { symbol: "PINS", name: "Pinterest Inc.", description: "Visual discovery and social media platform for ideas and inspiration.", assetType: "stock" },
  { symbol: "SNAP", name: "Snap Inc.", description: "Operates Snapchat, a multimedia messaging and social media app.", assetType: "stock" },
  { symbol: "TWLO", name: "Twilio Inc.", description: "Cloud communications platform for messaging, voice, and video APIs.", assetType: "stock" },
  { symbol: "DELL", name: "Dell Technologies Inc.", description: "Manufactures personal computers, servers, and enterprise IT infrastructure.", assetType: "stock" },
  { symbol: "HPQ", name: "HP Inc.", description: "Manufactures personal computers and printers.", assetType: "stock" },
  { symbol: "ANET", name: "Arista Networks Inc.", description: "Designs high-performance networking equipment for data centers.", assetType: "stock" },
  { symbol: "MSI", name: "Motorola Solutions Inc.", description: "Provides mission-critical communications equipment for public safety and enterprise.", assetType: "stock" },
  { symbol: "GRMN", name: "Garmin Ltd.", description: "Makes GPS navigation and wearable fitness devices.", assetType: "stock" },
  { symbol: "ADSK", name: "Autodesk Inc.", description: "Makes AutoCAD and other design software for architecture, engineering, and media.", assetType: "stock" },
  { symbol: "CDNS", name: "Cadence Design Systems Inc.", description: "Provides software tools used to design semiconductor chips.", assetType: "stock" },
  { symbol: "SNPS", name: "Synopsys Inc.", description: "Provides electronic design automation software for chip design.", assetType: "stock" },

  // Financials
  { symbol: "JPM", name: "JPMorgan Chase & Co.", description: "One of the largest banks in the US, offering consumer banking, investment banking, and asset management.", assetType: "stock" },
  { symbol: "V", name: "Visa Inc.", description: "Operates one of the world's largest electronic payment networks.", assetType: "stock" },
  { symbol: "MA", name: "Mastercard Inc.", description: "Global payments technology company that processes electronic transactions between banks and merchants.", assetType: "stock" },
  { symbol: "BAC", name: "Bank of America Corp.", description: "One of the largest banks in the US, offering consumer, commercial, and investment banking services.", assetType: "stock" },
  { symbol: "GS", name: "Goldman Sachs Group Inc.", description: "Global investment bank providing services in trading, asset management, and advisory.", assetType: "stock" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", description: "Digital payments platform enabling online money transfers between individuals and businesses.", assetType: "stock" },
  { symbol: "MS", name: "Morgan Stanley", description: "Global investment bank offering wealth management, trading, and advisory services.", assetType: "stock" },
  { symbol: "C", name: "Citigroup Inc.", description: "Global bank offering consumer banking, institutional banking, and wealth management.", assetType: "stock" },
  { symbol: "WFC", name: "Wells Fargo & Co.", description: "One of the largest US banks, offering retail and commercial banking services.", assetType: "stock" },
  { symbol: "AXP", name: "American Express Co.", description: "Payment card company and issuer offering credit cards and travel services.", assetType: "stock" },
  { symbol: "SCHW", name: "Charles Schwab Corp.", description: "Brokerage and banking company offering investing and wealth management services.", assetType: "stock" },
  { symbol: "BLK", name: "BlackRock Inc.", description: "The world's largest asset manager, known for its iShares ETFs.", assetType: "stock" },
  { symbol: "SPGI", name: "S&P Global Inc.", description: "Provides credit ratings, benchmarks, and financial market data, including the S&P 500 index.", assetType: "stock" },
  { symbol: "CME", name: "CME Group Inc.", description: "Operates futures and options exchanges for commodities, rates, and equities.", assetType: "stock" },
  { symbol: "CB", name: "Chubb Ltd.", description: "Global property and casualty insurance company.", assetType: "stock" },
  { symbol: "PGR", name: "Progressive Corp.", description: "Auto and home insurance provider known for direct-to-consumer marketing.", assetType: "stock" },
  { symbol: "TRV", name: "Travelers Companies Inc.", description: "Provides property, casualty, and specialty insurance products.", assetType: "stock" },
  { symbol: "MET", name: "MetLife Inc.", description: "Provides life insurance, annuities, and employee benefits.", assetType: "stock" },
  { symbol: "PRU", name: "Prudential Financial Inc.", description: "Provides life insurance, annuities, and investment management services.", assetType: "stock" },
  { symbol: "USB", name: "U.S. Bancorp", description: "Regional bank holding company offering consumer and commercial banking.", assetType: "stock" },
  { symbol: "PNC", name: "PNC Financial Services Group Inc.", description: "Regional bank offering retail and corporate banking services.", assetType: "stock" },
  { symbol: "COF", name: "Capital One Financial Corp.", description: "Bank holding company known for credit cards, auto loans, and retail banking.", assetType: "stock" },
  { symbol: "BX", name: "Blackstone Inc.", description: "The world's largest alternative asset manager, investing in private equity and real estate.", assetType: "stock" },
  { symbol: "KKR", name: "KKR & Co. Inc.", description: "Global investment firm specializing in private equity and alternative assets.", assetType: "stock" },

  // Healthcare
  { symbol: "UNH", name: "UnitedHealth Group Inc.", description: "Health insurance and healthcare services company, one of the largest in the US.", assetType: "stock" },
  { symbol: "JNJ", name: "Johnson & Johnson", description: "Healthcare company spanning pharmaceuticals, medical devices, and consumer health products.", assetType: "stock" },
  { symbol: "PFE", name: "Pfizer Inc.", description: "Pharmaceutical company developing vaccines and treatments across multiple therapeutic areas.", assetType: "stock" },
  { symbol: "ABT", name: "Abbott Laboratories", description: "Healthcare company producing medical devices, diagnostics, and nutritional products.", assetType: "stock" },
  { symbol: "LLY", name: "Eli Lilly and Co.", description: "Pharmaceutical company known for diabetes and weight-loss drugs like Mounjaro and Zepbound.", assetType: "stock" },
  { symbol: "MRK", name: "Merck & Co. Inc.", description: "Pharmaceutical company known for oncology drug Keytruda and vaccines.", assetType: "stock" },
  { symbol: "ABBV", name: "AbbVie Inc.", description: "Pharmaceutical company known for Humira and other immunology and oncology drugs.", assetType: "stock" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", description: "Makes scientific instruments and supplies for research and diagnostics.", assetType: "stock" },
  { symbol: "DHR", name: "Danaher Corp.", description: "Life sciences and diagnostics company serving biotech and medical research.", assetType: "stock" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Co.", description: "Pharmaceutical company focused on oncology, immunology, and cardiovascular drugs.", assetType: "stock" },
  { symbol: "AMGN", name: "Amgen Inc.", description: "Biotechnology company developing therapies for cancer, bone disease, and inflammation.", assetType: "stock" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", description: "Biopharmaceutical company known for HIV and antiviral treatments.", assetType: "stock" },
  { symbol: "CVS", name: "CVS Health Corp.", description: "Operates pharmacies, health insurance, and healthcare clinics.", assetType: "stock" },
  { symbol: "CI", name: "Cigna Group", description: "Health insurance and pharmacy benefits management company.", assetType: "stock" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", description: "Makes the da Vinci robotic surgical system.", assetType: "stock" },
  { symbol: "MDT", name: "Medtronic PLC", description: "Manufactures medical devices including pacemakers and surgical equipment.", assetType: "stock" },
  { symbol: "SYK", name: "Stryker Corp.", description: "Manufactures orthopedic implants and surgical equipment.", assetType: "stock" },
  { symbol: "BSX", name: "Boston Scientific Corp.", description: "Manufactures medical devices for cardiology and endoscopy.", assetType: "stock" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", description: "Biotechnology company known for Eylea and other antibody-based drugs.", assetType: "stock" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", description: "Biotechnology company focused on cystic fibrosis and other serious diseases.", assetType: "stock" },
  { symbol: "MRNA", name: "Moderna Inc.", description: "Biotechnology company known for its mRNA COVID-19 vaccine and pipeline.", assetType: "stock" },
  { symbol: "HCA", name: "HCA Healthcare Inc.", description: "Operates hospitals and healthcare facilities across the US.", assetType: "stock" },

  // Consumer
  { symbol: "WMT", name: "Walmart Inc.", description: "The world's largest retailer by revenue, operating supercenters and a growing e-commerce business.", assetType: "stock" },
  { symbol: "PG", name: "Procter & Gamble Co.", description: "Consumer goods company behind brands like Tide, Pampers, and Gillette.", assetType: "stock" },
  { symbol: "HD", name: "Home Depot Inc.", description: "The largest home improvement retailer in the US, serving both DIY customers and contractors.", assetType: "stock" },
  { symbol: "DIS", name: "Walt Disney Co.", description: "Entertainment company spanning film studios, theme parks, and streaming through Disney+.", assetType: "stock" },
  { symbol: "NFLX", name: "Netflix Inc.", description: "Subscription streaming service offering movies, TV shows, and original productions worldwide.", assetType: "stock" },
  { symbol: "KO", name: "Coca-Cola Co.", description: "Beverage company known for Coca-Cola and a wide portfolio of soft drinks, juices, and water brands.", assetType: "stock" },
  { symbol: "PEP", name: "PepsiCo Inc.", description: "Food and beverage company behind Pepsi, Lay's, Gatorade, and Quaker brands.", assetType: "stock" },
  { symbol: "NKE", name: "Nike Inc.", description: "Designs and markets athletic footwear, apparel, and equipment worldwide.", assetType: "stock" },
  { symbol: "MCD", name: "McDonald's Corp.", description: "The world's largest fast-food restaurant chain by revenue, operating primarily through franchises.", assetType: "stock" },
  { symbol: "COST", name: "Costco Wholesale Corp.", description: "Membership-based warehouse retailer selling bulk goods at discounted prices.", assetType: "stock" },
  { symbol: "SBUX", name: "Starbucks Corp.", description: "The world's largest coffeehouse chain, operating company-owned and licensed stores globally.", assetType: "stock" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", description: "Home improvement retailer serving DIY customers and professional contractors.", assetType: "stock" },
  { symbol: "TGT", name: "Target Corp.", description: "General merchandise retailer operating discount department stores.", assetType: "stock" },
  { symbol: "TJX", name: "TJX Companies Inc.", description: "Off-price retailer operating T.J. Maxx, Marshalls, and HomeGoods.", assetType: "stock" },
  { symbol: "YUM", name: "Yum! Brands Inc.", description: "Parent company of KFC, Pizza Hut, and Taco Bell.", assetType: "stock" },
  { symbol: "CMG", name: "Chipotle Mexican Grill Inc.", description: "Fast-casual restaurant chain known for made-to-order Mexican food.", assetType: "stock" },
  { symbol: "MO", name: "Altria Group Inc.", description: "Tobacco company that sells Marlboro cigarettes and other nicotine products in the US.", assetType: "stock" },
  { symbol: "PM", name: "Philip Morris International Inc.", description: "Sells Marlboro and other tobacco products, including IQOS heated tobacco, outside the US.", assetType: "stock" },
  { symbol: "CL", name: "Colgate-Palmolive Co.", description: "Consumer products company known for Colgate toothpaste and household brands.", assetType: "stock" },
  { symbol: "KMB", name: "Kimberly-Clark Corp.", description: "Makes Kleenex, Huggies, and other personal care paper products.", assetType: "stock" },
  { symbol: "GIS", name: "General Mills Inc.", description: "Packaged food company known for Cheerios, Betty Crocker, and Pillsbury.", assetType: "stock" },
  { symbol: "MDLZ", name: "Mondelez International Inc.", description: "Snack food company known for Oreo, Cadbury, and Ritz crackers.", assetType: "stock" },
  { symbol: "HSY", name: "Hershey Co.", description: "Confectionery company known for Hershey's chocolate and Reese's.", assetType: "stock" },
  { symbol: "KHC", name: "Kraft Heinz Co.", description: "Packaged food company known for Kraft, Heinz, and Oscar Mayer brands.", assetType: "stock" },
  { symbol: "EL", name: "Estee Lauder Companies Inc.", description: "Manufactures and markets prestige skincare, makeup, and fragrance brands.", assetType: "stock" },
  { symbol: "LULU", name: "Lululemon Athletica Inc.", description: "Designs and sells athletic apparel and accessories.", assetType: "stock" },
  { symbol: "MAR", name: "Marriott International Inc.", description: "The world's largest hotel chain by number of properties.", assetType: "stock" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings Inc.", description: "Global hospitality company operating hotel brands worldwide.", assetType: "stock" },
  { symbol: "RCL", name: "Royal Caribbean Cruises Ltd.", description: "Operates cruise lines including Royal Caribbean and Celebrity Cruises.", assetType: "stock" },
  { symbol: "UBER", name: "Uber Technologies Inc.", description: "Ride-hailing and delivery platform connecting riders, drivers, and couriers worldwide.", assetType: "stock" },

  // Industrials
  { symbol: "BA", name: "Boeing Co.", description: "Manufactures commercial airplanes and defense, space, and security systems.", assetType: "stock" },
  { symbol: "CAT", name: "Caterpillar Inc.", description: "Manufactures construction and mining equipment, engines, and industrial machinery.", assetType: "stock" },
  { symbol: "HON", name: "Honeywell International Inc.", description: "Diversified industrial company making aerospace, building, and safety technologies.", assetType: "stock" },
  { symbol: "UPS", name: "United Parcel Service Inc.", description: "Package delivery and supply chain management company.", assetType: "stock" },
  { symbol: "FDX", name: "FedEx Corp.", description: "Global courier delivery and logistics services company.", assetType: "stock" },
  { symbol: "LMT", name: "Lockheed Martin Corp.", description: "Defense contractor known for fighter jets and missile systems.", assetType: "stock" },
  { symbol: "RTX", name: "RTX Corp.", description: "Aerospace and defense company formed from Raytheon and United Technologies.", assetType: "stock" },
  { symbol: "NOC", name: "Northrop Grumman Corp.", description: "Defense contractor specializing in aerospace and defense electronics.", assetType: "stock" },
  { symbol: "GD", name: "General Dynamics Corp.", description: "Defense contractor building submarines, combat vehicles, and business jets.", assetType: "stock" },
  { symbol: "DE", name: "Deere & Co.", description: "Manufactures agricultural, construction, and forestry equipment under the John Deere brand.", assetType: "stock" },
  { symbol: "MMM", name: "3M Co.", description: "Diversified manufacturer of industrial, safety, and consumer products.", assetType: "stock" },
  { symbol: "GE", name: "GE Aerospace", description: "Manufactures jet engines and aerospace propulsion systems.", assetType: "stock" },
  { symbol: "EMR", name: "Emerson Electric Co.", description: "Manufactures automation equipment and industrial technology.", assetType: "stock" },
  { symbol: "ETN", name: "Eaton Corp. PLC", description: "Manufactures electrical equipment and power management products.", assetType: "stock" },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", description: "Diversified manufacturer of engineered products and industrial equipment.", assetType: "stock" },
  { symbol: "UNP", name: "Union Pacific Corp.", description: "Operates one of the largest freight railroads in the US.", assetType: "stock" },
  { symbol: "CSX", name: "CSX Corp.", description: "Operates freight rail transportation in the eastern United States.", assetType: "stock" },
  { symbol: "WM", name: "Waste Management Inc.", description: "Provides waste collection, recycling, and disposal services.", assetType: "stock" },

  // Energy & Utilities
  { symbol: "XOM", name: "Exxon Mobil Corp.", description: "Major oil and gas company involved in exploration, production, and refining worldwide.", assetType: "stock" },
  { symbol: "CVX", name: "Chevron Corp.", description: "Integrated oil and gas company involved in exploration, refining, and marketing.", assetType: "stock" },
  { symbol: "COP", name: "ConocoPhillips", description: "Oil and gas exploration and production company.", assetType: "stock" },
  { symbol: "SLB", name: "SLB (Schlumberger)", description: "Provides technology and services to the oil and gas industry.", assetType: "stock" },
  { symbol: "EOG", name: "EOG Resources Inc.", description: "Explores for and produces crude oil and natural gas in the US.", assetType: "stock" },
  { symbol: "PSX", name: "Phillips 66", description: "Refines and markets petroleum products and operates pipelines.", assetType: "stock" },
  { symbol: "MPC", name: "Marathon Petroleum Corp.", description: "Operates oil refineries and a network of fuel pipelines.", assetType: "stock" },
  { symbol: "VLO", name: "Valero Energy Corp.", description: "One of the largest independent petroleum refiners in the US.", assetType: "stock" },
  { symbol: "KMI", name: "Kinder Morgan Inc.", description: "Operates oil and natural gas pipelines and storage terminals.", assetType: "stock" },
  { symbol: "NEE", name: "NextEra Energy Inc.", description: "Electric utility and one of the largest generators of wind and solar power.", assetType: "stock" },
  { symbol: "DUK", name: "Duke Energy Corp.", description: "Electric and natural gas utility serving the southeastern US.", assetType: "stock" },
  { symbol: "SO", name: "Southern Co.", description: "Electric and natural gas utility serving the southeastern US.", assetType: "stock" },
  { symbol: "D", name: "Dominion Energy Inc.", description: "Electric and natural gas utility serving Virginia and the Carolinas.", assetType: "stock" },
  { symbol: "AEP", name: "American Electric Power Co.", description: "One of the largest electric utility companies in the US.", assetType: "stock" },

  // Communication
  { symbol: "T", name: "AT&T Inc.", description: "Telecommunications company providing wireless, broadband, and media services.", assetType: "stock" },
  { symbol: "VZ", name: "Verizon Communications Inc.", description: "Major US telecommunications provider offering wireless and broadband services.", assetType: "stock" },
  { symbol: "CMCSA", name: "Comcast Corp.", description: "Media and telecommunications company that owns NBCUniversal and Xfinity.", assetType: "stock" },
  { symbol: "CHTR", name: "Charter Communications Inc.", description: "Provides cable television, internet, and phone services under the Spectrum brand.", assetType: "stock" },
  { symbol: "TMUS", name: "T-Mobile US Inc.", description: "Wireless telecommunications carrier in the United States.", assetType: "stock" },
  { symbol: "WBD", name: "Warner Bros. Discovery Inc.", description: "Media company operating HBO, CNN, and Warner Bros. film studios.", assetType: "stock" },

  // Real Estate & Materials
  { symbol: "AMT", name: "American Tower Corp.", description: "Real estate investment trust that owns and operates wireless communication towers.", assetType: "stock" },
  { symbol: "PLD", name: "Prologis Inc.", description: "Real estate investment trust specializing in logistics and warehouse facilities.", assetType: "stock" },
  { symbol: "EQIX", name: "Equinix Inc.", description: "Real estate investment trust operating data centers worldwide.", assetType: "stock" },
  { symbol: "PSA", name: "Public Storage", description: "Real estate investment trust operating self-storage facilities.", assetType: "stock" },
  { symbol: "SPG", name: "Simon Property Group Inc.", description: "Real estate investment trust that owns shopping malls and outlet centers.", assetType: "stock" },
  { symbol: "LIN", name: "Linde PLC", description: "Industrial gases company supplying oxygen, nitrogen, and hydrogen worldwide.", assetType: "stock" },
  { symbol: "SHW", name: "Sherwin-Williams Co.", description: "Manufactures and sells paints, coatings, and related products.", assetType: "stock" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc.", description: "Mining company that produces copper, gold, and molybdenum.", assetType: "stock" },
  { symbol: "NEM", name: "Newmont Corp.", description: "The world's largest gold mining company.", assetType: "stock" },

  // Other well-known names
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc.", description: "Diversified holding company led by Warren Buffett, with stakes in insurance, railroads, and consumer brands.", assetType: "stock" },
];

export const ALL_CRYPTO: StockInfo[] = [
  { symbol: "BTC", name: "Bitcoin", description: "The original and largest cryptocurrency by market value, often treated as digital gold.", assetType: "crypto", quoteSymbol: "BINANCE:BTCUSDT", candleSymbol: "BTC/USD" },
  { symbol: "ETH", name: "Ethereum", description: "A programmable blockchain that powers smart contracts, DeFi, and NFTs.", assetType: "crypto", quoteSymbol: "BINANCE:ETHUSDT", candleSymbol: "ETH/USD" },
  { symbol: "SOL", name: "Solana", description: "A high-throughput blockchain designed for fast, low-cost transactions.", assetType: "crypto", quoteSymbol: "BINANCE:SOLUSDT", candleSymbol: "SOL/USD" },
  { symbol: "BNB", name: "BNB", description: "The native token of the BNB Chain ecosystem and Binance exchange.", assetType: "crypto", quoteSymbol: "BINANCE:BNBUSDT", candleSymbol: "BNB/USD" },
  { symbol: "XRP", name: "XRP", description: "A digital asset built for fast, low-cost cross-border payments, associated with Ripple.", assetType: "crypto", quoteSymbol: "BINANCE:XRPUSDT", candleSymbol: "XRP/USD" },
  { symbol: "ADA", name: "Cardano", description: "A proof-of-stake blockchain platform focused on research-driven development.", assetType: "crypto", quoteSymbol: "BINANCE:ADAUSDT", candleSymbol: "ADA/USD" },
  { symbol: "DOGE", name: "Dogecoin", description: "A meme-origin cryptocurrency that has become a widely traded payment token.", assetType: "crypto", quoteSymbol: "BINANCE:DOGEUSDT", candleSymbol: "DOGE/USD" },
  { symbol: "AVAX", name: "Avalanche", description: "A fast smart-contract blockchain platform built for decentralized apps.", assetType: "crypto", quoteSymbol: "BINANCE:AVAXUSDT", candleSymbol: "AVAX/USD" },
  { symbol: "DOT", name: "Polkadot", description: "A blockchain protocol designed to connect and secure multiple specialized chains.", assetType: "crypto", quoteSymbol: "BINANCE:DOTUSDT", candleSymbol: "DOT/USD" },
  { symbol: "LINK", name: "Chainlink", description: "A decentralized oracle network that connects smart contracts to real-world data.", assetType: "crypto", quoteSymbol: "BINANCE:LINKUSDT", candleSymbol: "LINK/USD" },
  { symbol: "LTC", name: "Litecoin", description: "An early Bitcoin fork designed for faster block times and lower fees.", assetType: "crypto", quoteSymbol: "BINANCE:LTCUSDT", candleSymbol: "LTC/USD" },
  { symbol: "POL", name: "Polygon", description: "A scaling network for Ethereum offering faster and cheaper transactions.", assetType: "crypto", quoteSymbol: "BINANCE:POLUSDT", candleSymbol: "POL/USD" },
  { symbol: "UNI", name: "Uniswap", description: "The governance token of Uniswap, the largest decentralized crypto exchange.", assetType: "crypto", quoteSymbol: "BINANCE:UNIUSDT", candleSymbol: "UNI/USD" },
  { symbol: "ATOM", name: "Cosmos", description: "A network of interoperable blockchains built to communicate with each other.", assetType: "crypto", quoteSymbol: "BINANCE:ATOMUSDT", candleSymbol: "ATOM/USD" },
  { symbol: "XLM", name: "Stellar", description: "A blockchain network designed for fast, low-cost cross-border payments.", assetType: "crypto", quoteSymbol: "BINANCE:XLMUSDT", candleSymbol: "XLM/USD" },
  { symbol: "ETC", name: "Ethereum Classic", description: "The original Ethereum chain, maintained after the 2016 DAO hard fork split.", assetType: "crypto", quoteSymbol: "BINANCE:ETCUSDT", candleSymbol: "ETC/USD" },
  { symbol: "NEAR", name: "NEAR Protocol", description: "A developer-friendly blockchain platform built for scalability.", assetType: "crypto", quoteSymbol: "BINANCE:NEARUSDT", candleSymbol: "NEAR/USD" },
  { symbol: "APT", name: "Aptos", description: "A high-performance layer-1 blockchain built with the Move programming language.", assetType: "crypto", quoteSymbol: "BINANCE:APTUSDT", candleSymbol: "APT/USD" },
  { symbol: "ARB", name: "Arbitrum", description: "A layer-2 scaling network that reduces the cost of Ethereum transactions.", assetType: "crypto", quoteSymbol: "BINANCE:ARBUSDT", candleSymbol: "ARB/USD" },
  { symbol: "OP", name: "Optimism", description: "A layer-2 scaling network built on Ethereum using optimistic rollups.", assetType: "crypto", quoteSymbol: "BINANCE:OPUSDT", candleSymbol: "OP/USD" },
];

export const ALL_ASSETS: StockInfo[] = [...ALL_STOCKS, ...ALL_CRYPTO];

// A small curated subset shown on the Dashboard by default,
// to keep API usage low on the homepage
export const WATCHED_STOCKS: StockInfo[] = ALL_ASSETS.filter((s) =>
  ["AAPL", "TSLA", "NVDA", "MSFT", "AMZN", "BTC", "ETH"].includes(s.symbol)
);
